# Generated by Django 4.1.3 on 2022-11-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='description',
            new_name='descripcion',
        ),
    ]
