# Generated by Django 4.1.3 on 2022-11-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0002_rename_description_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de animal')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=100, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo de animal')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=100, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Juguetes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imagen')),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
                ('categoria', models.CharField(max_length=100, null=True, verbose_name='Categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
